# Generated by Django 3.2.6 on 2021-11-26 08:07

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.manager.UserAccountManager()),
            ],
        ),
    ]
