export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAIL='SIGNUP_FAIL';
export const ACTIVATION_SUCCESS='ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL='ACTIVATION_FAIL';
export const USER_LOAD_SUCCESS='LOAD_USER_SUCCESS';
export const USER_LOAD_FAIL='LOAD_USER_FAIL';
export const AUTHENTICATED_SUCCESS='AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL='AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL='AUTHENTICATED_FAIL';
export const PASSWORD_RESET_SUCCESS='AUTHENTICATED_FAIL';
export const PASSWORD_RESET_CONFIRM_FAIL='AUTHENTICATED_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS='AUTHENTICATED_FAIL';
export const GOOGLE_AUTH_SUCCESS='GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL='GOOGLE_AUTH_FAIL';
export const LOGOUT='LOGOUT';

